"""Adding lots of features

Revision ID: 73bc73e69b2e
Revises: a64198d951cc
Create Date: 2022-02-27 11:38:18.010141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bc73e69b2e'
down_revision = 'a64198d951cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_queries',
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('keyword'),
    sa.UniqueConstraint('keyword')
    )
    op.add_column('movie_request', sa.Column('imdb_URL', sa.String(length=100), nullable=False))
    op.add_column('movie_request', sa.Column('posterLink', sa.String(length=100), nullable=False))
    op.add_column('movie_request', sa.Column('requestor', sa.String(length=100), nullable=False))
    op.add_column('movie_request', sa.Column('isfulfilled', sa.Boolean(), nullable=False))
    op.add_column('movie_request', sa.Column('status', sa.String(length=100), nullable=True))
    op.drop_constraint('movie_request_imdb_id_key', 'movie_request', type_='unique')
    op.create_unique_constraint(None, 'movie_request', ['imdb_URL'])
    op.create_unique_constraint(None, 'movie_request', ['posterLink'])
    op.drop_column('movie_request', 'imdb_id')
    op.create_unique_constraint(None, 'saved_movies', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_movies', type_='unique')
    op.add_column('movie_request', sa.Column('imdb_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'movie_request', type_='unique')
    op.drop_constraint(None, 'movie_request', type_='unique')
    op.create_unique_constraint('movie_request_imdb_id_key', 'movie_request', ['imdb_id'])
    op.drop_column('movie_request', 'status')
    op.drop_column('movie_request', 'isfulfilled')
    op.drop_column('movie_request', 'requestor')
    op.drop_column('movie_request', 'posterLink')
    op.drop_column('movie_request', 'imdb_URL')
    op.drop_table('saved_queries')
    # ### end Alembic commands ###
