"""Removing unique constrains in saved_movies table

Revision ID: a141dc7c6f98
Revises: 73bc73e69b2e
Create Date: 2022-03-13 19:55:36.616401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a141dc7c6f98'
down_revision = '73bc73e69b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('saved_movies_omdb_data_key', 'saved_movies', type_='unique')
    op.drop_constraint('saved_movies_tmdb_data_key', 'saved_movies', type_='unique')
    op.create_unique_constraint(None, 'saved_queries', ['keyword'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_queries', type_='unique')
    op.create_unique_constraint('saved_movies_tmdb_data_key', 'saved_movies', ['tmdb_data'])
    op.create_unique_constraint('saved_movies_omdb_data_key', 'saved_movies', ['omdb_data'])
    # ### end Alembic commands ###
