"""empty message

Revision ID: a64198d951cc
Revises: 
Create Date: 2022-02-23 15:53:50.446724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64198d951cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_movies',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('imdb_id', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.String(length=100), nullable=False),
    sa.Column('tmdb_data', sa.Text(), nullable=False),
    sa.Column('omdb_data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('omdb_data'),
    sa.UniqueConstraint('tmdb_data')
    )
    op.create_unique_constraint(None, 'movie', ['id'])
    op.create_unique_constraint(None, 'movie_request', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_request', type_='unique')
    op.drop_constraint(None, 'movie', type_='unique')
    op.drop_table('saved_movies')
    # ### end Alembic commands ###
