from threading import Thread

class CustomThread(Thread):
    def __init__(self, group=None, target=None, name=None,
                 args=(), kwargs={}, Verbose=None):
        Thread.__init__(self, group, target, name, args, kwargs)
        self._return = None
    def run(self):
        print(type(self._target))
        if self._target is not None:
            self._return = self._target(*self._args,
                                                **self._kwargs)
    def join(self, *args):
        Thread.join(self, *args)
        return self._return


omdb_info={'Title': 'Your Name.',
            'Year': '2016',
            'Rated': 'TV-PG',
            'Released': '07 Apr 2017',
            'Runtime': '106 min',
            'Genre': 'Animation, Drama, Fantasy',
            'Director': 'Makoto Shinkai',
            'Writer': 'Makoto Shinkai, Clark Cheng',
            'Actors': 'Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Narita',
            'Plot': 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
            'Language': 'Japanese',
            'Country': 'Japan',
            'Awards': '16 wins & 26 nominations',
            'Poster': 'https://m.media-amazon.com/images/M/MV5BODRmZDVmNzUtZDA4ZC00NjhkLWI2M2UtN2M0ZDIzNDcxYThjL2ltYWdlXkEyXkFqcGdeQXVyNTk0MzMzODA@._V1_SX300.jpg',
            'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.4/10'},
            {'Source': 'Rotten Tomatoes', 'Value': '98%'},
            {'Source': 'Metacritic', 'Value': '79/100'}],
            'Metascore': '79',
            'imdbRating': '8.4',
            'imdbVotes': '240,992',
            'imdbID': 'tt5311514',
            'Type': 'movie',
            'DVD': '31 Jan 2018',
            'BoxOffice': '$5,017,246',
            'Production': 'N/A',
            'Website': 'N/A',
            'Response': 'True'}
tmdb_info = {'adult': False,
                'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
                'belongs_to_collection': None,
                'budget': 0,
                'genres': [{'id': 10749, 'name': 'Romance'},
                {'id': 16, 'name': 'Animation'},
                {'id': 18, 'name': 'Drama'}],
                'homepage': 'https://www.funimationfilms.com/movie/yourname/',
                'id': 372058,
                'imdb_id': 'tt5311514',
                'original_language': 'ja',
                'original_title': '君の名は。',
                'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
                'popularity': 168.815,
                'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
                'production_companies': [{'id': 3756,
                'logo_path': '/t38uPdbKmyBB8brKKeTFWIwojRz.png',
                'name': 'CoMix Wave Films',
                'origin_country': 'JP'},
                {'id': 882,
                'logo_path': '/fRSWWjquvzcHjACbtF53utZFIll.png',
                'name': 'Toho',
                'origin_country': 'JP'},
                {'id': 2073,
                'logo_path': '/6KxDcBObqIPRgns95Vdo6sjRtXQ.png',
                'name': 'Kadokawa',
                'origin_country': 'JP'},
                {'id': 8157,
                'logo_path': '/yHOC2PPmj6j2zzRqwdufCZauFxI.png',
                'name': 'East Japan Marketing & Communications',
                'origin_country': 'JP'},
                {'id': 14602,
                'logo_path': '/t9eqx5QCHtu8LxxgYzivqrJAosp.png',
                'name': 'AMUSE',
                'origin_country': 'JP'},
                {'id': 128617,
                'logo_path': None,
                'name': 'voque ting',
                'origin_country': 'JP'},
                {'id': 104184,
                'logo_path': None,
                'name': 'Lawson Entertainment',
                'origin_country': 'JP'}],
                'production_countries': [{'iso_3166_1': 'JP', 'name': 'Japan'}],
                'release_date': '2016-08-26',
                'revenue': 357986087,
                'runtime': 106,
                'spoken_languages': [{'english_name': 'Japanese',
                'iso_639_1': 'ja',
                'name': '日本語'}],
                'status': 'Released',
                'tagline': '',
                'title': 'Your Name.',
                'video': False,
                'vote_average': 8.5,
                'vote_count': 8371}